### ISSUE TITLE
Coloring

### ISSUE THREAD

**Issue by MaeseppTarvo** [4taras4/CountryCode#17]
Hey guys. Awesome library, however I have one little problem.

I added it as a inputView to make it appear like keyboard. But like this it is impossible to change it's color. Do you know any solution for this?

You can check out the detailed problem description from [here](https://stackoverflow.com/questions/45085104/changing-inputview-background-color-from-blurry-gray-to-anything-else).

**Comment by 4taras4** [comment]
It's very easy just set the background color for picker view in your Storyboard 
<img width="1139" alt="2017-07-22 13 40 21" src="https://user-images.githubusercontent.com/6876979/28490500-07ec13d0-6ee4-11e7-9003-9d2476bd94a6.png">
