### ISSUE TITLE
Incorect Kkazakhstan country code

### ISSUE THREAD

**Issue by moon4ik** [4taras4/CountryCode#20]
Please check the Kazakhstan country code.
They have two: +7-6xx, +7-7xx. In your picker +77. 
I think you should change from +77 to +7.
https://countrycode.org/kazakhstan

PS. Дякую

**Comment by 4taras4** [comment]
Hello, already fixed, install pod using commit -21bb7eb6bef1bb3bcdee251fcf76486c7aee0799
Thank you for using my library
