### ISSUE TITLE
Question Marks are displaying

### ISSUE THREAD

**Issue by nAkhmedov** [4taras4/CountryCode#21]
I am using 1.4.5 version Xcode 9 and  getting question mark list only
<img width="200" alt="screen shot 2017-11-03 at 5 48 45 pm" src="https://user-images.githubusercontent.com/8067423/32374501-db148a8a-c0bf-11e7-945a-e3655564e200.png">

**Comment by 4taras4** [comment]
@nAkhmedov try reinstall pod

**Comment by nAkhmedov** [comment]
no luck

**Comment by 4taras4** [comment]
try new version 1.7.1
