### ISSUE TITLE
Objective-c compatibility 

### ISSUE THREAD

**Issue by CavalcanteLeo** [4taras4/CountryCode#22]
Delegates and properties are not visible in objective-c.

![captura de tela 2017-11-17 as 16 17 36](https://user-images.githubusercontent.com/1735944/32962229-d99f0d58-cbb2-11e7-9bfa-fbf38cedd7c9.png)

**Comment by brightfuture** [comment]
This OC library might be what you want:
https://github.com/nicklockwood/CountryPicker

**Comment by 4taras4** [comment]
@brightfuture  yes this one was inspired by objective-c version
