### ISSUE TITLE
Value of type 'CountryPicker' has no member 'displayOnlyCountriesWithCodes' ISSUE

### ISSUE THREAD

**Issue by krishcdbry** [4taras4/CountryCode#28]
Not working giving error

`Value of type 'CountryPicker' has no member 'displayOnlyCountriesWithCodes'`

did I miss anything?

<img width="381" alt="screen shot 2018-03-05 at 2 47 35 am" src="https://user-images.githubusercontent.com/4358385/36950687-b33cb81a-201f-11e8-9e51-0a2341022707.png">

**Comment by 4taras4** [comment]
Fixed in 1.7 also added exept countries
