### ISSUE TITLE
Problem When installing 

### ISSUE THREAD

**Issue by cs4alhaider** [4taras4/CountryCode#33]
I run pod install and it says 

> [!] Unable to find a specification for `CountryPickerSwift`

**Comment by 4taras4** [comment]
Try to update pod repository

pod repo update
If doesn't help show log from

pod install --verbose
Edit:

try to add

source 'https://github.com/CocoaPods/Specs.git'
to your Podfile. If doesn't help probably there is a problem with your local pod repo. You can fix this using:

pod repo remove master
pod setup
pod install

**Comment by cs4alhaider** [comment]
pod repo remove master
pod setup
pod install

That actually works! Thanks alot for the help and for the framework

**Comment by 4taras4** [comment]
Thank you for using my framework
