### ISSUE TITLE
Wrong result when tapping on already selected row

### ISSUE THREAD

**Issue by IPv6** [4taras4/CountryCode#38]
Currenlty delegate recevies wrong values, when users taps on selected row in picker.
Delegate receives data for country 0, but app expects to see data for country actually tapped (in selected row)

**Comment by AhmedSamir213** [comment]
same issue here

**Comment by shalomFUn** [comment]
Very same issue here also

**Comment by udaysingh2** [comment]
me too faced the same issue

**Comment by 4taras4** [comment]
fixed 1.7.4

**Comment by AhmedSamir213** [comment]
i installed 1.7.4 but issue still the same issue

**Comment by snehageorge** [comment]
I installed 1.8.0 still facing the same issue

**Comment by anurajdl** [comment]
Facing the same issue with 1.8.0

**Comment by snehageorge** [comment]
@4taras4 Still facing the same issue with 1.8.0
