### ISSUE TITLE
Crash while building release version

### ISSUE THREAD

**Issue by yulian948** [4taras4/CountryCode#41]
After updating to 1.7.3 I got this crash when building my app in release mode: 
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/3232DF58-CCEB-491A-8387-7100A0D31587/fototax.app/Frameworks/CountryPicker.framework> (loaded)' with name 'CountryView''

**Comment by jfredsilva** [comment]
I also have this crash, it's also happening on dev on a real device. If I use the simulator it doesn't crash.

**Comment by toothpiggystudio** [comment]
sam here... i got this error on simulator and actual device.

as of the moment i downgraded it to 1.7.1 and it works fine.

pod 'CountryPickerSwift', '1.7.1'

**Comment by 4taras4** [comment]
fixed 1.7.4
