### ISSUE TITLE
No access to the CountryPicker using SPM

### ISSUE THREAD

**Issue by DmitryShapovalov** [4taras4/CountryCode#62]
Hello.

I am trying to integrate a library using the Swift Package Manager from the master branch, everything looks good, but there is no way to access the source files for CountryPicker, only for the dummy CountryCode struct.

**Comment by DmitryShapovalov** [comment]
FYI @4taras4

**Comment by 4taras4** [comment]
@DmitryShapovalov Fixed SPM
